### ISSUE TITLE
Error "Reduce" when signing out

### ISSUE THREAD

**Issue by Gehrkej** [Golf-Drill-Challenge-App/Golf-App#193]
### Description
When testing functionality around removing a user, I found when I would use the sign out button, I would receive the error in the attached Screenshot

### Steps to reproduce

1. Create a new user _(Updated)_
2. Navigate to the profile page
3. Click the settings icon
4. Press the sign out button

### Screenshot
![image](https://github.com/Golf-Drill-Challenge-App/Golf-App/assets/91503842/804c7eac-0065-4714-92ff-948b71c4287c)

**Comment by solderq35** [comment]
https://github.com/Golf-Drill-Challenge-App/Golf-App/blob/layout/app/content/assignments/index.js#L45

I'm guessing that userInfo is undefined here, triggering the error

**Comment by solderq35** [comment]
Jake's explanation of triggering the error:
- open app on two devices, one of them logged in as coach, one as player
- coach removes the player
- player automatically logs in again (from login persistence in context/Auth.js) and gets error shown (assignments page)
  - unclear what happens if logged out user tries to log in normally (type in username and password)

**Comment by Gehrkej** [comment]
Not sure if this is still happening as I was able to sign out without getting this error message but instead recieved a " ERROR  [TypeError: Cannot read property 'uid' of null]" error... Will try to include more information as I am testing #190 and signing out of accounts frequently

**Comment by Gehrkej** [comment]
was able to reproduce this error actually upon testing. 

- Create a new user.
- Go to profile tab
- click settings icon
- Click signout

**Comment by solderq35** [comment]
Should be fixed by PR linked above, closing as completed
