### ISSUE TITLE
Nav Bar (bottom / top)

### ISSUE THREAD

**Issue by ajpert** [Golf-Drill-Challenge-App/Golf-App#40]

**Comment by solderq35** [comment]
As referenced here (https://github.com/Golf-Drill-Challenge-App/Golf-App/pull/48#discussion_r1468205826), we are currently merging a PR to establish the general file structure of the app, following Expo Router framework. 

Expo Router has a built-in Tabs component for bottom-tab navigation, with dynamic routing support (https://docs.expo.dev/router/advanced/tabs/#dynamic-routes). 

Andy worked on this as well last week (https://github.com/Golf-Drill-Challenge-App/Golf-App/pull/42), but we have since made other changes into the `layout/navigation` branch (main branch we are merging into), and also I'm not sure if the BottomTabNavigator he used (from React-Navigation) is exactly the same as Expo Router's Tabs component.

So we need to look into reconciling Andy's PR with the changes in `layout/navigation`, and also check where best to put any component files needed for top navbar (which might only be used on some pages).

**Comment by solderq35** [comment]
My work on this issue this week - https://github.com/Golf-Drill-Challenge-App/Golf-App/pull/60
